#!/bin/bash

# Prints out battery percentage

CHARGING_ICON=''
WARNING_ICON=' '
BATTERY_FULL_ICON=''
BATTERY_2_ICON=''
BATTERY_3_ICON=''
BATTERY_4_ICON=''

FULL_AT=98

BAT_ICON=""
ICON=""

get_battery()
{
	# The vast majority of people only use one battery.

	if [ -d /sys/class/power_supply/BAT0 ]; then
		capacity=$(cat /sys/class/power_supply/BAT0/capacity)
		charging=$(cat /sys/class/power_supply/BAT0/status)
		if [[ "$charging" == "Charging" ]]; then
			ICON="$CHARGING_ICON"
		elif [[ $capacity -le 25 ]]; then
			ICON="$WARNING_ICON"
		fi

    COLOR_RESET="\x0b"
    COLOR="\x0b"

		if [[ $capacity -ge $FULL_AT ]]; then
			BAT_ICON=$BATTERY_FULL_ICON
      COLOR=$COLOR_RESET
		elif [[ $capacity -le 10 ]]; then
      BAT_ICON="$BATTERY_4_ICON"
      COLOR="\x0d"
		elif [[ $capacity -le 25 ]]; then
      BAT_ICON="$BATTERY_4_ICON"
      COLOR="\x0c"
    elif [[ $capacity -le 60 ]]; then
			BAT_ICON=$BATTERY_3_ICON
      COLOR=$COLOR_RESET
		elif [[ $capacity -le $FULL_AT ]]; then
			BAT_ICON=$BATTERY_2_ICON
      COLOR=$COLOR_RESET
		fi
	fi
	echo -e "$ICON$BAT_ICON $COLOR$capacity%$COLOR_RESET"
}

get_battery
