#!/bin/bash

# Prints out the CPU load percentage

PREFIX=''
MI_START=40
HI_START=80

get_load()
{
  # Get the first line with aggregate of all CPUs
  cpu_last=($(head -n1 /proc/stat))
  cpu_last_sum="${cpu_last[@]:1}"
  cpu_last_sum=$((${cpu_last_sum// /+}))

  sleep 0.05

  cpu_now=($(head -n1 /proc/stat))
  cpu_sum="${cpu_now[@]:1}"
  cpu_sum=$((${cpu_sum// /+}))

  cpu_delta=$((cpu_sum - cpu_last_sum))
  cpu_idle=$((cpu_now[4]- cpu_last[4]))
  cpu_used=$((cpu_delta - cpu_idle))
  cpu_usage=$((100 * cpu_used / cpu_delta))

  # Keep this as last for our next read
  cpu_last=("${cpu_now[@]}")
  cpu_last_sum=$cpu_sum

  cpu_usage=$(printf %02d ${cpu_usage})

  COLOR_RESET="\x0b"
  COLOR="\x0b"

		if [[ $cpu_usage -ge $HI_START ]]; then
      COLOR="\x0f"
		elif [[ $cpu_usage -ge $MI_START ]]; then
      COLOR="\x0e"
    fi

  echo -e "$COLOR$PREFIX $cpu_usage%$COLOR_RESET"
}

get_load
