#!/bin/bash

# Gets the wifi status
WIRED_IF_PREFIX="enp"
WIRED_IF_PATH_PREFIX="/sys/class/net"
WIRED_IF_PATH_SUFFIX="carrier"

WIRED_ICON='󰛳'

get_wired()
{
  while IFS= read -r i; do
    if grep -q "1" $i ; then
      echo -n "${WIRED_ICON}"
      return
    fi
  done <<< $(ls -1 ${WIRED_IF_PATH_PREFIX}/${WIRED_IF_PREFIX}*/${WIRED_IF_PATH_SUFFIX})
}

get_wired
